In [ ]:
# This dataset contains occurrence records and other environmental information 
# about arthropod prey species, taken from cleaned GBIF data. 
# Accessed on October 1, 2026, from https://knb.ecoinformatics.org/view/doi%3A10.5063%2FF1VM49RH


# Rachel King, Jenna Braun, Michael Westphal, & CJ Lortie. (2023). 
# Compiled occurrence records for prey items of listed species found in California drylands with associated environmental data. 
# Knowledge Network for Biocomplexity. doi:10.5063/F1VM49RH.

In [2]:
import pandas as pd 
import os

In [3]:
# Access metadata from repository
fp = os.path.join('data', 'metadata_arth_occurrences.csv')
meta = pd.read_csv(fp)

In [4]:
# Access prey data 
preyfp = os.path.join('data','arth_occurrences_with_env.csv')
prey = pd.read_csv(preyfp)
prey

,class,order,family,genus,species,lat,long,eventDate,day,month,...,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
0,Insecta,Odonata,Libellulidae,Sympetrum,Sympetrum corruptum,37.173971,-121.856329,2020-09-29T08:24:00Z,29.0,9.0,...,4352.049805,289.341888,27.307756,262.034149,89.602631,196.067307,8.935099,352.799927,grassland,6343.969238
1,Malacostraca,Isopoda,Armadillidiidae,Armadillidium,Armadillidium vulgare,37.688580,-122.436608,2021-12-04T14:49:59Z,4.0,12.0,...,2455.836914,217.470047,61.847702,155.622360,107.227386,159.852875,2.005335,112.895271,grassland,4995.110352
2,Insecta,Hymenoptera,Apidae,Bombus,Bombus vosnesenskii,33.774911,-116.679713,2021-06-18T08:52:00Z,18.0,6.0,...,5776.527344,254.696030,-47.440784,302.136810,20.866125,134.750717,4.422367,2315.607666,grassland,5118.055664
3,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,32.848001,-117.050126,2016-04-17T09:28:00Z,17.0,4.0,...,3539.726807,286.711762,65.920944,220.790817,133.117722,213.238907,4.316342,199.882156,closed_shrubland,3649.374756
4,Insecta,Hemiptera,Lygaeidae,Oncopeltus,Oncopeltus fasciatus,32.739453,-117.133980,2019-04-06T18:44:31Z,6.0,4.0,...,3033.009521,259.712738,81.205818,178.506927,138.277557,205.749908,0.651661,72.789574,urban,3468.256104
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18897,Malacostraca,Isopoda,Armadillidiidae,Armadillidium,Armadillidium vulgare,33.843311,-118.161762,2019-03-23T11:02:29Z,23.0,3.0,...,3379.020752,284.856690,75.528175,209.328522,141.968781,217.416077,1.624954,17.065048,urban,2904.818359
18898,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,37.769031,-122.497998,2020-09-11T16:25:00Z,11.0,9.0,...,2270.484131,213.580383,64.090378,149.490005,110.609818,156.728928,1.019553,79.828819,evergreen_needleleaf,4565.072754
18899,Insecta,Hymenoptera,Formicidae,Liometopum,Liometopum occidentale,38.680117,-121.020426,2022-05-13T13:21:41Z,13.0,5.0,...,6201.473633,338.523041,20.217506,318.305542,77.328346,232.318848,3.257940,367.381409,savanna,4606.991699
18900,Insecta,Diptera,Syrphidae,Allograpta,Allograpta obliqua,34.054771,-118.272527,2020-03-31T11:57:09Z,31.0,3.0,...,3357.900146,290.119659,81.679710,208.439957,145.409409,221.075241,1.096267,87.851532,urban,1710.356567
18901,Malacostraca,Decapoda,Grapsidae,Pachygrapsus,Pachygrapsus crassipes,36.812905,-121.768905,2021-11-11T14:06:48Z,11.0,11.0,...,2631.293457,236.430786,42.675713,193.755081,103.214410,NaN,NaN,NaN,NaN,NaN

In [5]:
type(prey)

pandas.core.frame.DataFrame

In [6]:
prey

,class,order,family,genus,species,lat,long,eventDate,day,month,...,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
0,Insecta,Odonata,Libellulidae,Sympetrum,Sympetrum corruptum,37.173971,-121.856329,2020-09-29T08:24:00Z,29.0,9.0,...,4352.049805,289.341888,27.307756,262.034149,89.602631,196.067307,8.935099,352.799927,grassland,6343.969238
1,Malacostraca,Isopoda,Armadillidiidae,Armadillidium,Armadillidium vulgare,37.688580,-122.436608,2021-12-04T14:49:59Z,4.0,12.0,...,2455.836914,217.470047,61.847702,155.622360,107.227386,159.852875,2.005335,112.895271,grassland,4995.110352
2,Insecta,Hymenoptera,Apidae,Bombus,Bombus vosnesenskii,33.774911,-116.679713,2021-06-18T08:52:00Z,18.0,6.0,...,5776.527344,254.696030,-47.440784,302.136810,20.866125,134.750717,4.422367,2315.607666,grassland,5118.055664
3,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,32.848001,-117.050126,2016-04-17T09:28:00Z,17.0,4.0,...,3539.726807,286.711762,65.920944,220.790817,133.117722,213.238907,4.316342,199.882156,closed_shrubland,3649.374756
4,Insecta,Hemiptera,Lygaeidae,Oncopeltus,Oncopeltus fasciatus,32.739453,-117.133980,2019-04-06T18:44:31Z,6.0,4.0,...,3033.009521,259.712738,81.205818,178.506927,138.277557,205.749908,0.651661,72.789574,urban,3468.256104
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18897,Malacostraca,Isopoda,Armadillidiidae,Armadillidium,Armadillidium vulgare,33.843311,-118.161762,2019-03-23T11:02:29Z,23.0,3.0,...,3379.020752,284.856690,75.528175,209.328522,141.968781,217.416077,1.624954,17.065048,urban,2904.818359
18898,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,37.769031,-122.497998,2020-09-11T16:25:00Z,11.0,9.0,...,2270.484131,213.580383,64.090378,149.490005,110.609818,156.728928,1.019553,79.828819,evergreen_needleleaf,4565.072754
18899,Insecta,Hymenoptera,Formicidae,Liometopum,Liometopum occidentale,38.680117,-121.020426,2022-05-13T13:21:41Z,13.0,5.0,...,6201.473633,338.523041,20.217506,318.305542,77.328346,232.318848,3.257940,367.381409,savanna,4606.991699
18900,Insecta,Diptera,Syrphidae,Allograpta,Allograpta obliqua,34.054771,-118.272527,2020-03-31T11:57:09Z,31.0,3.0,...,3357.900146,290.119659,81.679710,208.439957,145.409409,221.075241,1.096267,87.851532,urban,1710.356567
18901,Malacostraca,Decapoda,Grapsidae,Pachygrapsus,Pachygrapsus crassipes,36.812905,-121.768905,2021-11-11T14:06:48Z,11.0,11.0,...,2631.293457,236.430786,42.675713,193.755081,103.214410,NaN,NaN,NaN,NaN,NaN

In [9]:
pd.set_option("display.max_columns", None)
prey

,class,order,family,genus,species,lat,long,eventDate,day,month,year,institutionCode,coordinateUncertaintyInMeters,basisOfRecord,individualCount,datasetKey,ID,bio1,bio10,bio11,bio12,bio13,bio14,bio15,bio16,bio17,bio18,bio19,bio2,bio3,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
0,Insecta,Odonata,Libellulidae,Sympetrum,Sympetrum corruptum,37.173971,-121.856329,2020-09-29T08:24:00Z,29.0,9.0,2020,iNaturalist,684.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,1,141.925064,199.384964,89.602631,727.380493,151.920853,1.809903,89.132339,391.141083,7.979710,13.979711,391.141083,139.787125,53.000000,4352.049805,289.341888,27.307756,262.034149,89.602631,196.067307,8.935099,352.799927,grassland,6343.969238
1,Malacostraca,Isopoda,Armadillidiidae,Armadillidium,Armadillidium vulgare,37.688580,-122.436608,2021-12-04T14:49:59Z,4.0,12.0,2021,iNaturalist,6.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,2,136.366943,165.841537,104.141464,609.651916,126.271736,1.001933,87.368050,318.303192,8.236301,12.390024,318.301269,83.996452,53.266750,2455.836914,217.470047,61.847702,155.622360,107.227386,159.852875,2.005335,112.895271,grassland,4995.110352
2,Insecta,Hymenoptera,Apidae,Bombus,Bombus vosnesenskii,33.774911,-116.679713,2021-06-18T08:52:00Z,18.0,6.0,2021,iNaturalist,31.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,3,82.885788,161.338638,19.747343,724.200195,120.836441,4.910511,70.099121,353.376068,49.060783,77.778824,342.061676,144.624817,47.098640,5776.527344,254.696030,-47.440784,302.136810,20.866125,134.750717,4.422367,2315.607666,grassland,5118.055664
3,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,32.848001,-117.050126,2016-04-17T09:28:00Z,17.0,4.0,2016,iNaturalist,15.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,4,171.959030,221.238907,130.363754,323.523682,62.686253,1.000000,87.075172,179.273834,4.989321,9.743295,163.154465,118.763413,53.612831,3539.726807,286.711762,65.920944,220.790817,133.117722,213.238907,4.316342,199.882156,closed_shrubland,3649.374756
4,Insecta,Hemiptera,Lygaeidae,Oncopeltus,Oncopeltus fasciatus,32.739453,-117.133980,2019-04-06T18:44:31Z,6.0,4.0,2019,iNaturalist,16.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,5,171.996231,214.353073,136.138779,273.203491,58.141060,1.000000,91.661606,162.390411,4.000000,7.109778,142.560562,91.184349,50.718666,3033.009521,259.712738,81.205818,178.506927,138.277557,205.749908,0.651661,72.789574,urban,3468.256104
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18897,Malacostraca,Isopoda,Armadillidiidae,Armadillidium,Armadillidium vulgare,33.843311,-118.161762,2019-03-23T11:02:29Z,23.0,3.0,2019,iNaturalist,65.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,18898,178.459396,224.899994,137.968781,322.556335,71.459389,0.000000,95.956688,194.637558,3.000000,8.483921,186.787567,110.881218,52.483921,3379.020752,284.856690,75.528175,209.328522,141.968781,217.416077,1.624954,17.065048,urban,2904.818359
18898,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,37.769031,-122.497998,2020-09-11T16:25:00Z,11.0,9.0,2020,iNaturalist,250.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,18899,136.639145,163.736069,106.220810,640.238098,134.406250,1.000000,88.252632,338.067505,8.872323,52.527489,337.461609,79.722107,52.922325,2270.484131,213.580383,64.090378,149.490005,110.609818,156.728928,1.019553,79.828819,evergreen_needleleaf,4565.072754
18899,Insecta,Hymenoptera,Formicidae,Liometopum,Liometopum occidentale,38.680117,-121.020426,2022-05-13T13:21:41Z,13.0,5.0,2022,iNaturalist,4.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,18900,152.558701,233.318848,77.328346,785.118957,163.117722,1.810155,83.384552,412.961609,13.364868,18.271509,412.961609,141.125183,43.819649,6201.473633,338.523041,20.217506,318.305542,77.328346,232.318848,3.257940,367.381409,savanna,4606.991699
18900,Insecta,Diptera,Syrphidae,Allograpta,Allograpta obliqua,34.054771,-118.272527,2020-03-31T11:57:09Z,31.0,3.0,2020,iNaturalist,22.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,18901,181.726929,228.075241,142.409409,381.008606,86.426315,0.000000,99.389725,242.172699,4.952777,11.676928,222.660523,113.668594,54.000000,3357.900146,290.119659,81.679710,208.439957,145.409409,221.075241,1.096267,87.851532,urban,1710.356567
18901,Malacostraca,Decapoda,Grapsidae,Pachygrapsus,Pachygrapsus crassipes,36.812905,-121.768905,2021-11-11T14:06:48Z,11.0,11.0,2021,iNaturalist,6.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,18902,138.214371,169.556305,103.214416,449.450714,95.590897,1.000000,89.159973,245.308197,6.000000,9.000000,245.308197,116.595207,60.000000,2631.293457,236.430786,42.675713,193.755081,103.214410,NaN,NaN,NaN,NaN,NaN

In [ ]:
git st