In [ ]:
# This dataset contains occurrence records and other environmental information 
# about arthropod prey species, taken from cleaned GBIF data. 
# Accessed on October 1, 2026, from https://knb.ecoinformatics.org/view/doi%3A10.5063%2FF1VM49RH


# Rachel King, Jenna Braun, Michael Westphal, & CJ Lortie. (2023). 
# Compiled occurrence records for prey items of listed species found in California drylands with associated environmental data. 
# Knowledge Network for Biocomplexity. doi:10.5063/F1VM49RH.

In [2]:
import pandas as pd 
import os

In [3]:
# Access metadata from repository
fp = os.path.join('data', 'metadata_arth_occurrences.csv')
meta = pd.read_csv(fp)

In [4]:
# Access prey data 
preyfp = os.path.join('data','arth_occurrences_with_env.csv')
prey = pd.read_csv(preyfp)
prey

,class,order,family,genus,species,lat,long,eventDate,day,month,...,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
0,Insecta,Odonata,Libellulidae,Sympetrum,Sympetrum corruptum,37.173971,-121.856329,2020-09-29T08:24:00Z,29.0,9.0,...,4352.049805,289.341888,27.307756,262.034149,89.602631,196.067307,8.935099,352.799927,grassland,6343.969238
1,Malacostraca,Isopoda,Armadillidiidae,Armadillidium,Armadillidium vulgare,37.688580,-122.436608,2021-12-04T14:49:59Z,4.0,12.0,...,2455.836914,217.470047,61.847702,155.622360,107.227386,159.852875,2.005335,112.895271,grassland,4995.110352
2,Insecta,Hymenoptera,Apidae,Bombus,Bombus vosnesenskii,33.774911,-116.679713,2021-06-18T08:52:00Z,18.0,6.0,...,5776.527344,254.696030,-47.440784,302.136810,20.866125,134.750717,4.422367,2315.607666,grassland,5118.055664
3,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,32.848001,-117.050126,2016-04-17T09:28:00Z,17.0,4.0,...,3539.726807,286.711762,65.920944,220.790817,133.117722,213.238907,4.316342,199.882156,closed_shrubland,3649.374756
4,Insecta,Hemiptera,Lygaeidae,Oncopeltus,Oncopeltus fasciatus,32.739453,-117.133980,2019-04-06T18:44:31Z,6.0,4.0,...,3033.009521,259.712738,81.205818,178.506927,138.277557,205.749908,0.651661,72.789574,urban,3468.256104
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18897,Malacostraca,Isopoda,Armadillidiidae,Armadillidium,Armadillidium vulgare,33.843311,-118.161762,2019-03-23T11:02:29Z,23.0,3.0,...,3379.020752,284.856690,75.528175,209.328522,141.968781,217.416077,1.624954,17.065048,urban,2904.818359
18898,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,37.769031,-122.497998,2020-09-11T16:25:00Z,11.0,9.0,...,2270.484131,213.580383,64.090378,149.490005,110.609818,156.728928,1.019553,79.828819,evergreen_needleleaf,4565.072754
18899,Insecta,Hymenoptera,Formicidae,Liometopum,Liometopum occidentale,38.680117,-121.020426,2022-05-13T13:21:41Z,13.0,5.0,...,6201.473633,338.523041,20.217506,318.305542,77.328346,232.318848,3.257940,367.381409,savanna,4606.991699
18900,Insecta,Diptera,Syrphidae,Allograpta,Allograpta obliqua,34.054771,-118.272527,2020-03-31T11:57:09Z,31.0,3.0,...,3357.900146,290.119659,81.679710,208.439957,145.409409,221.075241,1.096267,87.851532,urban,1710.356567
18901,Malacostraca,Decapoda,Grapsidae,Pachygrapsus,Pachygrapsus crassipes,36.812905,-121.768905,2021-11-11T14:06:48Z,11.0,11.0,...,2631.293457,236.430786,42.675713,193.755081,103.214410,NaN,NaN,NaN,NaN,NaN

In [5]:
type(prey)

pandas.core.frame.DataFrame

In [6]:
prey

,class,order,family,genus,species,lat,long,eventDate,day,month,...,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
0,Insecta,Odonata,Libellulidae,Sympetrum,Sympetrum corruptum,37.173971,-121.856329,2020-09-29T08:24:00Z,29.0,9.0,...,4352.049805,289.341888,27.307756,262.034149,89.602631,196.067307,8.935099,352.799927,grassland,6343.969238
1,Malacostraca,Isopoda,Armadillidiidae,Armadillidium,Armadillidium vulgare,37.688580,-122.436608,2021-12-04T14:49:59Z,4.0,12.0,...,2455.836914,217.470047,61.847702,155.622360,107.227386,159.852875,2.005335,112.895271,grassland,4995.110352
2,Insecta,Hymenoptera,Apidae,Bombus,Bombus vosnesenskii,33.774911,-116.679713,2021-06-18T08:52:00Z,18.0,6.0,...,5776.527344,254.696030,-47.440784,302.136810,20.866125,134.750717,4.422367,2315.607666,grassland,5118.055664
3,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,32.848001,-117.050126,2016-04-17T09:28:00Z,17.0,4.0,...,3539.726807,286.711762,65.920944,220.790817,133.117722,213.238907,4.316342,199.882156,closed_shrubland,3649.374756
4,Insecta,Hemiptera,Lygaeidae,Oncopeltus,Oncopeltus fasciatus,32.739453,-117.133980,2019-04-06T18:44:31Z,6.0,4.0,...,3033.009521,259.712738,81.205818,178.506927,138.277557,205.749908,0.651661,72.789574,urban,3468.256104
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18897,Malacostraca,Isopoda,Armadillidiidae,Armadillidium,Armadillidium vulgare,33.843311,-118.161762,2019-03-23T11:02:29Z,23.0,3.0,...,3379.020752,284.856690,75.528175,209.328522,141.968781,217.416077,1.624954,17.065048,urban,2904.818359
18898,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,37.769031,-122.497998,2020-09-11T16:25:00Z,11.0,9.0,...,2270.484131,213.580383,64.090378,149.490005,110.609818,156.728928,1.019553,79.828819,evergreen_needleleaf,4565.072754
18899,Insecta,Hymenoptera,Formicidae,Liometopum,Liometopum occidentale,38.680117,-121.020426,2022-05-13T13:21:41Z,13.0,5.0,...,6201.473633,338.523041,20.217506,318.305542,77.328346,232.318848,3.257940,367.381409,savanna,4606.991699
18900,Insecta,Diptera,Syrphidae,Allograpta,Allograpta obliqua,34.054771,-118.272527,2020-03-31T11:57:09Z,31.0,3.0,...,3357.900146,290.119659,81.679710,208.439957,145.409409,221.075241,1.096267,87.851532,urban,1710.356567
18901,Malacostraca,Decapoda,Grapsidae,Pachygrapsus,Pachygrapsus crassipes,36.812905,-121.768905,2021-11-11T14:06:48Z,11.0,11.0,...,2631.293457,236.430786,42.675713,193.755081,103.214410,NaN,NaN,NaN,NaN,NaN

In [9]:
pd.set_option("display.max_columns", None)
prey

,class,order,family,genus,species,lat,long,eventDate,day,month,year,institutionCode,coordinateUncertaintyInMeters,basisOfRecord,individualCount,datasetKey,ID,bio1,bio10,bio11,bio12,bio13,bio14,bio15,bio16,bio17,bio18,bio19,bio2,bio3,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
0,Insecta,Odonata,Libellulidae,Sympetrum,Sympetrum corruptum,37.173971,-121.856329,2020-09-29T08:24:00Z,29.0,9.0,2020,iNaturalist,684.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,1,141.925064,199.384964,89.602631,727.380493,151.920853,1.809903,89.132339,391.141083,7.979710,13.979711,391.141083,139.787125,53.000000,4352.049805,289.341888,27.307756,262.034149,89.602631,196.067307,8.935099,352.799927,grassland,6343.969238
1,Malacostraca,Isopoda,Armadillidiidae,Armadillidium,Armadillidium vulgare,37.688580,-122.436608,2021-12-04T14:49:59Z,4.0,12.0,2021,iNaturalist,6.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,2,136.366943,165.841537,104.141464,609.651916,126.271736,1.001933,87.368050,318.303192,8.236301,12.390024,318.301269,83.996452,53.266750,2455.836914,217.470047,61.847702,155.622360,107.227386,159.852875,2.005335,112.895271,grassland,4995.110352
2,Insecta,Hymenoptera,Apidae,Bombus,Bombus vosnesenskii,33.774911,-116.679713,2021-06-18T08:52:00Z,18.0,6.0,2021,iNaturalist,31.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,3,82.885788,161.338638,19.747343,724.200195,120.836441,4.910511,70.099121,353.376068,49.060783,77.778824,342.061676,144.624817,47.098640,5776.527344,254.696030,-47.440784,302.136810,20.866125,134.750717,4.422367,2315.607666,grassland,5118.055664
3,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,32.848001,-117.050126,2016-04-17T09:28:00Z,17.0,4.0,2016,iNaturalist,15.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,4,171.959030,221.238907,130.363754,323.523682,62.686253,1.000000,87.075172,179.273834,4.989321,9.743295,163.154465,118.763413,53.612831,3539.726807,286.711762,65.920944,220.790817,133.117722,213.238907,4.316342,199.882156,closed_shrubland,3649.374756
4,Insecta,Hemiptera,Lygaeidae,Oncopeltus,Oncopeltus fasciatus,32.739453,-117.133980,2019-04-06T18:44:31Z,6.0,4.0,2019,iNaturalist,16.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,5,171.996231,214.353073,136.138779,273.203491,58.141060,1.000000,91.661606,162.390411,4.000000,7.109778,142.560562,91.184349,50.718666,3033.009521,259.712738,81.205818,178.506927,138.277557,205.749908,0.651661,72.789574,urban,3468.256104
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18897,Malacostraca,Isopoda,Armadillidiidae,Armadillidium,Armadillidium vulgare,33.843311,-118.161762,2019-03-23T11:02:29Z,23.0,3.0,2019,iNaturalist,65.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,18898,178.459396,224.899994,137.968781,322.556335,71.459389,0.000000,95.956688,194.637558,3.000000,8.483921,186.787567,110.881218,52.483921,3379.020752,284.856690,75.528175,209.328522,141.968781,217.416077,1.624954,17.065048,urban,2904.818359
18898,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,37.769031,-122.497998,2020-09-11T16:25:00Z,11.0,9.0,2020,iNaturalist,250.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,18899,136.639145,163.736069,106.220810,640.238098,134.406250,1.000000,88.252632,338.067505,8.872323,52.527489,337.461609,79.722107,52.922325,2270.484131,213.580383,64.090378,149.490005,110.609818,156.728928,1.019553,79.828819,evergreen_needleleaf,4565.072754
18899,Insecta,Hymenoptera,Formicidae,Liometopum,Liometopum occidentale,38.680117,-121.020426,2022-05-13T13:21:41Z,13.0,5.0,2022,iNaturalist,4.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,18900,152.558701,233.318848,77.328346,785.118957,163.117722,1.810155,83.384552,412.961609,13.364868,18.271509,412.961609,141.125183,43.819649,6201.473633,338.523041,20.217506,318.305542,77.328346,232.318848,3.257940,367.381409,savanna,4606.991699
18900,Insecta,Diptera,Syrphidae,Allograpta,Allograpta obliqua,34.054771,-118.272527,2020-03-31T11:57:09Z,31.0,3.0,2020,iNaturalist,22.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,18901,181.726929,228.075241,142.409409,381.008606,86.426315,0.000000,99.389725,242.172699,4.952777,11.676928,222.660523,113.668594,54.000000,3357.900146,290.119659,81.679710,208.439957,145.409409,221.075241,1.096267,87.851532,urban,1710.356567
18901,Malacostraca,Decapoda,Grapsidae,Pachygrapsus,Pachygrapsus crassipes,36.812905,-121.768905,2021-11-11T14:06:48Z,11.0,11.0,2021,iNaturalist,6.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,18902,138.214371,169.556305,103.214416,449.450714,95.590897,1.000000,89.159973,245.308197,6.000000,9.000000,245.308197,116.595207,60.000000,2631.293457,236.430786,42.675713,193.755081,103.214410,NaN,NaN,NaN,NaN,NaN

In [17]:
prey.nunique()

class                                4
order                               15
family                              54
genus                               80
species                             84
lat                              17510
long                             17485
eventDate                        18374
day                                 31
month                               12
year                                73
institutionCode                     16
coordinateUncertaintyInMeters     1546
basisOfRecord                        3
individualCount                     11
datasetKey                          20
ID                               18902
bio1                              5253
bio10                             5329
bio11                             5268
bio12                             5373
bio13                             5358
bio14                             1838
bio15                             5270
bio16                             5370
bio17                             4073
bio18                             4804
bio19                             5368
bio2                              5344
bio3                              4145
bio4                              5372
bio5                              5343
bio6                              5336
bio7                              5370
bio8                              5316
bio9                              5330
dist                              5284
dem90_hf                          5268
lc_class                            12
ndvi                              9852
dtype: int64

In [ ]:
prey.info()

In [ ]:
prey.head()

In [ ]:
prey.tail()

In [20]:
prey.shape

(18902, 40)

In [21]:
prey.columns

Index(['class', 'order', 'family', 'genus', 'species', 'lat', 'long',
       'eventDate', 'day', 'month', 'year', 'institutionCode',
       'coordinateUncertaintyInMeters', 'basisOfRecord', 'individualCount',
       'datasetKey', 'ID', 'bio1', 'bio10', 'bio11', 'bio12', 'bio13', 'bio14',
       'bio15', 'bio16', 'bio17', 'bio18', 'bio19', 'bio2', 'bio3', 'bio4',
       'bio5', 'bio6', 'bio7', 'bio8', 'bio9', 'dist', 'dem90_hf', 'lc_class',
       'ndvi'],
      dtype='object')

In [23]:
prey.dtypes

class                             object
order                             object
family                            object
genus                             object
species                           object
lat                              float64
long                             float64
eventDate                         object
day                              float64
month                            float64
year                               int64
institutionCode                   object
coordinateUncertaintyInMeters    float64
basisOfRecord                     object
individualCount                  float64
datasetKey                        object
ID                                 int64
bio1                             float64
bio10                            float64
bio11                            float64
bio12                            float64
bio13                            float64
bio14                            float64
bio15                            float64
bio16                            float64
bio17                            float64
bio18                            float64
bio19                            float64
bio2                             float64
bio3                             float64
bio4                             float64
bio5                             float64
bio6                             float64
bio7                             float64
bio8                             float64
bio9                             float64
dist                             float64
dem90_hf                         float64
lc_class                          object
ndvi                             float64
dtype: object

In [25]:
prey = prey.rename(columns={"institutionCode" : "institution_code", "datasetKey":"dataset"})

In [26]:
prey

,class,order,family,genus,species,lat,long,eventDate,day,month,year,institution_code,coordinateUncertaintyInMeters,basisOfRecord,individualCount,dataset,ID,bio1,bio10,bio11,bio12,bio13,bio14,bio15,bio16,bio17,bio18,bio19,bio2,bio3,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
0,Insecta,Odonata,Libellulidae,Sympetrum,Sympetrum corruptum,37.173971,-121.856329,2020-09-29T08:24:00Z,29.0,9.0,2020,iNaturalist,684.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,1,141.925064,199.384964,89.602631,727.380493,151.920853,1.809903,89.132339,391.141083,7.979710,13.979711,391.141083,139.787125,53.000000,4352.049805,289.341888,27.307756,262.034149,89.602631,196.067307,8.935099,352.799927,grassland,6343.969238
1,Malacostraca,Isopoda,Armadillidiidae,Armadillidium,Armadillidium vulgare,37.688580,-122.436608,2021-12-04T14:49:59Z,4.0,12.0,2021,iNaturalist,6.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,2,136.366943,165.841537,104.141464,609.651916,126.271736,1.001933,87.368050,318.303192,8.236301,12.390024,318.301269,83.996452,53.266750,2455.836914,217.470047,61.847702,155.622360,107.227386,159.852875,2.005335,112.895271,grassland,4995.110352
2,Insecta,Hymenoptera,Apidae,Bombus,Bombus vosnesenskii,33.774911,-116.679713,2021-06-18T08:52:00Z,18.0,6.0,2021,iNaturalist,31.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,3,82.885788,161.338638,19.747343,724.200195,120.836441,4.910511,70.099121,353.376068,49.060783,77.778824,342.061676,144.624817,47.098640,5776.527344,254.696030,-47.440784,302.136810,20.866125,134.750717,4.422367,2315.607666,grassland,5118.055664
3,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,32.848001,-117.050126,2016-04-17T09:28:00Z,17.0,4.0,2016,iNaturalist,15.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,4,171.959030,221.238907,130.363754,323.523682,62.686253,1.000000,87.075172,179.273834,4.989321,9.743295,163.154465,118.763413,53.612831,3539.726807,286.711762,65.920944,220.790817,133.117722,213.238907,4.316342,199.882156,closed_shrubland,3649.374756
4,Insecta,Hemiptera,Lygaeidae,Oncopeltus,Oncopeltus fasciatus,32.739453,-117.133980,2019-04-06T18:44:31Z,6.0,4.0,2019,iNaturalist,16.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,5,171.996231,214.353073,136.138779,273.203491,58.141060,1.000000,91.661606,162.390411,4.000000,7.109778,142.560562,91.184349,50.718666,3033.009521,259.712738,81.205818,178.506927,138.277557,205.749908,0.651661,72.789574,urban,3468.256104
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18897,Malacostraca,Isopoda,Armadillidiidae,Armadillidium,Armadillidium vulgare,33.843311,-118.161762,2019-03-23T11:02:29Z,23.0,3.0,2019,iNaturalist,65.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,18898,178.459396,224.899994,137.968781,322.556335,71.459389,0.000000,95.956688,194.637558,3.000000,8.483921,186.787567,110.881218,52.483921,3379.020752,284.856690,75.528175,209.328522,141.968781,217.416077,1.624954,17.065048,urban,2904.818359
18898,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,37.769031,-122.497998,2020-09-11T16:25:00Z,11.0,9.0,2020,iNaturalist,250.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,18899,136.639145,163.736069,106.220810,640.238098,134.406250,1.000000,88.252632,338.067505,8.872323,52.527489,337.461609,79.722107,52.922325,2270.484131,213.580383,64.090378,149.490005,110.609818,156.728928,1.019553,79.828819,evergreen_needleleaf,4565.072754
18899,Insecta,Hymenoptera,Formicidae,Liometopum,Liometopum occidentale,38.680117,-121.020426,2022-05-13T13:21:41Z,13.0,5.0,2022,iNaturalist,4.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,18900,152.558701,233.318848,77.328346,785.118957,163.117722,1.810155,83.384552,412.961609,13.364868,18.271509,412.961609,141.125183,43.819649,6201.473633,338.523041,20.217506,318.305542,77.328346,232.318848,3.257940,367.381409,savanna,4606.991699
18900,Insecta,Diptera,Syrphidae,Allograpta,Allograpta obliqua,34.054771,-118.272527,2020-03-31T11:57:09Z,31.0,3.0,2020,iNaturalist,22.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,18901,181.726929,228.075241,142.409409,381.008606,86.426315,0.000000,99.389725,242.172699,4.952777,11.676928,222.660523,113.668594,54.000000,3357.900146,290.119659,81.679710,208.439957,145.409409,221.075241,1.096267,87.851532,urban,1710.356567
18901,Malacostraca,Decapoda,Grapsidae,Pachygrapsus,Pachygrapsus crassipes,36.812905,-121.768905,2021-11-11T14:06:48Z,11.0,11.0,2021,iNaturalist,6.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,18902,138.214371,169.556305,103.214416,449.450714,95.590897,1.000000,89.159973,245.308197,6.000000,9.000000,245.308197,116.595207,60.000000,2631.293457,236.430786,42.675713,193.755081,103.214410,NaN,NaN,NaN,NaN,NaN

In [40]:
preserved = prey[prey['basisOfRecord']== "PRESERVED_SPECIMEN"]
preserved['basisOfRecord'].value_counts()

basisOfRecord
PRESERVED_SPECIMEN    972
Name: count, dtype: int64

In [45]:
yearfilter = prey[prey['year'].between(1992,2000)]
yearfilter
# OR
prey_years=prey[(prey['year'] >= 1992) & (prey['year']<=2000)]
prey_years

,class,order,family,genus,species,lat,long,eventDate,day,month,year,institution_code,coordinateUncertaintyInMeters,basisOfRecord,individualCount,dataset,ID,bio1,bio10,bio11,bio12,bio13,bio14,bio15,bio16,bio17,bio18,bio19,bio2,bio3,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
1700,Insecta,Coleoptera,Tenebrionidae,Eleodes,Eleodes acuticauda,34.421123,-118.501387,1997-05-01T00:00:00Z,1.0,5.0,1997,UTEP,11109.0,PRESERVED_SPECIMEN,NaN,297ecc07-da20-4ebf-9f41-4f80330b4b33,1701,164.052139,233.923935,103.943611,430.573395,85.408524,1.000000,90.341942,243.386704,6.473931,14.473931,228.178177,150.136734,50.526070,5095.691895,325.297852,29.228207,296.069641,110.393616,228.634598,0.741066,429.214630,urban,2944.426025
1717,Insecta,Hymenoptera,Formicidae,Pogonomyrmex,Pogonomyrmex californicus,34.467772,-116.202715,1999-06-25T00:00:00Z,25.0,6.0,1999,UTEP,47736.0,PRESERVED_SPECIMEN,NaN,297ecc07-da20-4ebf-9f41-4f80330b4b33,1718,175.680969,273.335938,86.016029,184.159760,23.819201,1.000000,44.414768,67.621468,17.214769,38.254143,67.621468,160.409638,43.030281,7391.372070,377.030609,10.835779,366.194824,98.681000,203.801804,27.322420,965.792725,grassland,730.316284
1721,Insecta,Hymenoptera,Formicidae,Pogonomyrmex,Pogonomyrmex californicus,36.248500,-117.991028,1998-07-07T00:00:00Z,7.0,7.0,1998,UTEP,NaN,PRESERVED_SPECIMEN,NaN,297ecc07-da20-4ebf-9f41-4f80330b4b33,1722,147.054962,247.533112,52.613918,208.074432,36.672558,4.000000,66.227470,101.110840,16.957857,19.254721,100.493416,154.673431,41.000000,7639.830566,349.753693,-21.017378,370.771057,68.180321,222.533112,27.927256,1176.939453,open_shrubland,1639.310547
1732,Insecta,Orthoptera,Acrididae,Melanoplus,Melanoplus sanguinipes,38.826049,-120.108584,1998-10-11T00:00:00Z,11.0,10.0,1998,CSU,2000.0,PRESERVED_SPECIMEN,1.0,323b0e80-5e4b-4cc4-936a-d93fc8cae9bc,1733,47.266640,129.389542,-21.191164,1109.233276,189.963196,13.407290,70.784904,524.399963,57.491680,63.041679,515.479981,133.981216,43.549999,6100.312500,222.205154,-82.314064,304.519226,-10.491679,127.882248,2.310431,2385.305176,savanna,2616.363525
1734,Insecta,Orthoptera,Acrididae,Schistocerca,Schistocerca nitens,34.274568,-114.053159,1997-03-14T00:00:00Z,14.0,3.0,1997,CSU,2210.0,PRESERVED_SPECIMEN,1.0,323b0e80-5e4b-4cc4-936a-d93fc8cae9bc,1735,219.312576,323.291962,118.825050,148.716095,20.612474,1.020624,46.754322,51.566795,9.120624,33.216194,51.516796,160.712585,41.608150,8037.842773,417.879486,37.258148,380.621338,136.341949,253.241959,NaN,241.861481,open_shrubland,2594.753174
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5374,Insecta,Coleoptera,Melolonthidae,Polyphylla,Polyphylla decemlineata,34.463800,-119.743600,2000-06-09T00:00:00Z,9.0,6.0,2000,SBMNH,NaN,PRESERVED_SPECIMEN,1.0,d883d764-4522-4928-bdf7-4d6f0aae2ebd,5375,149.726975,197.654831,108.297424,526.453369,115.285377,0.000000,99.180885,317.866852,2.000000,7.413320,305.575043,120.276085,54.178745,3528.171631,265.641205,45.026978,220.614243,111.186615,191.586090,1.083591,229.868362,grassland,6043.500977
5408,Insecta,Coleoptera,Scarabaeidae,Canthon,Canthon simplex,33.250000,-116.770000,1998-03-15T00:00:00Z,15.0,3.0,1998,SBMNH,NaN,PRESERVED_SPECIMEN,1.0,d883d764-4522-4928-bdf7-4d6f0aae2ebd,5409,139.206131,217.035629,73.498398,569.850281,101.791542,2.832059,78.627884,297.992554,26.496178,39.943607,278.701721,150.966888,48.262878,5669.671875,314.742218,6.163673,308.578522,80.834282,188.720017,0.522245,949.128784,closed_shrubland,4451.394043
12003,Insecta,Hymenoptera,Apidae,Bombus,Bombus vosnesenskii,37.963434,-121.871347,1999-06-01T00:00:00Z,1.0,6.0,1999,MCZ,3145.0,PRESERVED_SPECIMEN,1.0,4bfac3ea-8763-4f4b-a71a-76a6f5f243d3,12004,149.992020,214.427948,85.457985,478.576202,99.966164,1.000000,85.412186,252.722229,6.251890,10.550000,252.722229,132.832153,48.000000,5070.254883,306.604004,31.015963,275.588043,85.457985,211.176056,14.880870,289.004791,grassland,4327.172363
16132,Insecta,Coleoptera,Chrysomelidae,Diabrotica,Diabrotica undecimpunctata,37.909400,-122.686400,1999-04-01T00:00:00Z,NaN,4.0,1999,NHMUK,NaN,PRESERVED_SPECIMEN,1.0,7e380070-f762-11e1-a439-00145eb45e9a,16133,133.506027,170.507111,94.953766,978.265015,204.940735,2.000000,89.592659,531.142944,13.000000,17.637972,522.834228,101.000061,54.831825,2983.158936,229.148438,45.967197,183.181244,99.442551,166.507111,2.064850,61.397858,woody_savanna,5950.313965
18064,Insecta,Hymenoptera,Formicidae,Liometopum,Liometopum occidentale,33.146863,-116.450542,1997-04-02T00:00:00Z,2.0,4.0,1997,MCZ,757.0,PRESERVED_SPECIMEN,2.0,4bfac3ea-8763-4f4b-a71a-76a6f5f243d3,18065,162.568695,245.049377,90.583145,366.457367,63.021721,2.000000,69.534317,181.570572,20.459043,40.409584,169.516403,164.566223,48.049999,6130.339844,352.554779,16.572329,335.982452,99.088013,216.024109,2.893340,790.271545,grassland,1823.659058

In [48]:
specieseventdate= prey[['species', 'eventDate']]
specieseventdate

                      species             eventDate
0         Sympetrum corruptum  2020-09-29T08:24:00Z
1       Armadillidium vulgare  2021-12-04T14:49:59Z
2         Bombus vosnesenskii  2021-06-18T08:52:00Z
3              Apis mellifera  2016-04-17T09:28:00Z
4        Oncopeltus fasciatus  2019-04-06T18:44:31Z
...                       ...                   ...
18897   Armadillidium vulgare  2019-03-23T11:02:29Z
18898          Apis mellifera  2020-09-11T16:25:00Z
18899  Liometopum occidentale  2022-05-13T13:21:41Z
18900      Allograpta obliqua  2020-03-31T11:57:09Z
18901  Pachygrapsus crassipes  2021-11-11T14:06:48Z

[18902 rows x 2 columns]

In [50]:
lat_filter = prey[(prey['lat'] >= 37) & (prey['lat']<=39)]
lat_filter

,class,order,family,genus,species,lat,long,eventDate,day,month,year,institution_code,coordinateUncertaintyInMeters,basisOfRecord,individualCount,dataset,ID,bio1,bio10,bio11,bio12,bio13,bio14,bio15,bio16,bio17,bio18,bio19,bio2,bio3,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
0,Insecta,Odonata,Libellulidae,Sympetrum,Sympetrum corruptum,37.173971,-121.856329,2020-09-29T08:24:00Z,29.0,9.0,2020,iNaturalist,684.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,1,141.925064,199.384964,89.602631,727.380493,151.920853,1.809903,89.132339,391.141083,7.979710,13.979711,391.141083,139.787125,53.000000,4352.049805,289.341888,27.307756,262.034149,89.602631,196.067307,8.935099,352.799927,grassland,6343.969238
1,Malacostraca,Isopoda,Armadillidiidae,Armadillidium,Armadillidium vulgare,37.688580,-122.436608,2021-12-04T14:49:59Z,4.0,12.0,2021,iNaturalist,6.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,2,136.366943,165.841537,104.141464,609.651916,126.271736,1.001933,87.368050,318.303192,8.236301,12.390024,318.301269,83.996452,53.266750,2455.836914,217.470047,61.847702,155.622360,107.227386,159.852875,2.005335,112.895271,grassland,4995.110352
5,Insecta,Diptera,Syrphidae,Allograpta,Allograpta obliqua,37.842187,-122.272478,2020-05-02T10:28:25Z,2.0,5.0,2020,iNaturalist,917.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,6,144.511795,178.412857,105.581818,565.076050,122.171043,1.000000,87.983589,308.378662,7.063087,9.205670,308.378662,89.164856,51.079494,2885.461670,234.265152,60.451580,173.813568,105.581818,172.760529,0.365533,35.971046,urban,3031.351807
9,Insecta,Lepidoptera,Nymphalidae,Vanessa,Vanessa cardui,37.323517,-122.174308,2019-04-29T15:22:16Z,29.0,4.0,2019,iNaturalist,5.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,10,131.805481,181.386352,89.509621,824.623535,164.044968,2.000000,86.375435,431.711121,11.555281,15.646415,431.711121,118.941368,54.445618,3672.007080,252.594223,35.436752,217.157471,89.509621,176.914505,1.444703,532.485596,evergreen_needleleaf,7056.129395
10,Insecta,Lepidoptera,Sphingidae,Hyles,Hyles lineata,38.412833,-121.421913,2020-03-27T07:12:56Z,27.0,3.0,2020,iNaturalist,65.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,11,158.215454,229.449997,82.928772,436.710846,94.928772,1.000000,86.713325,231.857544,6.000000,10.000000,231.857544,142.071228,46.286674,5830.274902,334.665436,30.430893,304.234558,82.928772,229.215454,2.179459,8.622081,urban,3572.570801
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18880,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,37.225514,-121.844794,2022-09-13T08:51:00Z,13.0,9.0,2022,iNaturalist,4.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,18881,150.293121,203.373428,95.867279,519.222717,109.928627,1.026208,88.597954,278.752045,5.078624,10.128624,278.752045,138.077881,53.497952,4235.796875,289.955780,33.819698,256.136078,95.867279,201.323425,2.283755,96.346451,grassland,4031.054932
18882,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,37.361299,-121.937644,2021-07-20T10:39:57Z,20.0,7.0,2021,iNaturalist,28417.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,18883,152.948517,201.349136,101.705818,386.428101,79.573219,1.000000,84.627853,202.209732,4.729714,9.000000,199.567764,121.718979,53.000000,3927.162842,273.948273,45.832100,228.116196,111.830170,198.512985,0.446281,21.579821,urban,2646.771484
18892,Insecta,Hymenoptera,Vespidae,Vespula,Vespula pensylvanica,37.366866,-121.835642,2019-04-12T10:49:00Z,12.0,4.0,2019,iNaturalist,28417.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,18893,152.707001,207.358170,97.348831,411.683319,85.170578,1.000000,86.965164,216.825745,4.210750,9.210750,216.825745,132.634659,51.789249,4339.862305,291.911163,38.880501,253.030670,97.348831,204.854996,0.679187,70.878410,urban,3212.031250
18898,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,37.769031,-122.497998,2020-09-11T16:25:00Z,11.0,9.0,2020,iNaturalist,250.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,18899,136.639145,163.736069,106.220810,640.238098,134.406250,1.000000,88.252632,338.067505,8.872323,52.527489,337.461609,79.722107,52.922325,2270.484131,213.580383,64.090378,149.490005,110.609818,156.728928,1.019553,79.828819,evergreen_needleleaf,4565.072754
18899,Insecta,Hymenoptera,Formicidae,Liometopum,Liometopum occidentale,38.680117,-121.020426,2022-05-13T13:21:41Z,13.0,5.0,2022,iNaturalist,4.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,18900,152.558701,233.318848,77.328346,785.118957,163.117722,1.810155,83.384552,412.961609,13.364868,18.271509,412.961609,141.125183,43.819649,6201.473633,338.523041,20.217506,318.305542,77.328346,232.318848,3.257940,367.381409,savanna,4606.991699